store_types = {
"Лекарства": ["Galen Pharm"],
"Приём врача": ["Family Medica"],
"Походы в кафе": ["Vesela Soova", "Ugostiteljska Radnja"],
"Ткань": ["Ogranak Vir Tex"],
"Икеа" : ["Ikea Beograd Istok"],
"Store": ["Lidl", "Univerexport", "Cash Carry Plus", "Maxi", "Mesara", "Medius", "Matijević", "Prodavnica Br. 0159", "Prodavnica Kalenić Pijaca", "1284848-P23", "Skladišno-Distributivni Centar Zemun", "Ikea Food", "Gigatron", "Mp015"]
}


simplificator = {
"Аксессуары для волос": ["snalica"],
"Ананас": ["ananas svez"],
"Апельсины": ["pomorandza"],
"Бананы": ["banana"],
"Бреф": ["bref"],
"Булгур": ["bulgur"],
"Бурда": ["burda"],
"Валерьянка": ["valeriana"],
"Ванилин": ["vanil secer"],
"Варенье малиновое": ["slatko malina"],
"Витамины": ["magnezijum", "omega3"],
"Влажные салфетки": ["vl.maramice"],
"Выпечка": ["strudla"],
"Газировка": ["sok gazirani","aloe ver", "fanta", "7 up", "sprite", "dryck", "iskub", "lotte"],
"Гель для душа": ["gel tus", "tus gel"],
"Говядина": ["juneci but", "juneći but", "juneća rebra", "angus", "ramstek"],
"Готовая еда на обед": ["sarma"],
"Гречка": ["heljda"],
"Груши": ["kruska"],
"Дрожжи": ["kvasac"],
"Жевательная резинка": ["zvake", "orbit"],
"Желатин": ["zelatin"],
"Земля": ["zemlja"],
"Зубные щётки": ["cetka za zube"],
"Йогурт в баночке": ["jogurt grekos", "dukatos jogurt"],
"Йогурт питьевой": ["jogurt 2.8%mm", "jogurt lagani", "dukat jogurt", "kravica gusti"],
"Йогурт сладкий": ["jogood"],
"Канцтовары": ["selotejp traka", "koverte", "fascikla", "skalper", "spajalice", "stipaljke"],
"Капуста": ["kupus"],
"Картошка": ["krompir"],
"Кетчуп": ["kecap"],
"Кефир": ["kefir"],
"Киви": ["kivi"],
"Клейкая лента": ["lepljiva traka"],
"Колбаса": ["mortadel", "salama", "kobasica", "sunka"],
"Кондиционер для стирки": ["lenor"],
"Кокос": ["kokos napitak"],
"Конфеты": ["haribo", "praline"],
"Кости на суп": ["junece mesnate kosti"],
"Кофе": ["nescafe", "caffe carra"],
"Креветки": ["gambori"],
"Круассаны": ["7days", "7 days"],
"Курица":["pile ", "pileca krila", "pileca src", "batak"],
"Лимонная кислота":["limuntus"],
"Лук": ["crni luk", "luk mladi", "luk crni"],
"Майонез": ["majonez"],
"Макароны": ["nudle", "testenina", "fusilli", "makarone", "barilla"],
"Масло сливочное": ["maslac", "puter"],
"Мебель": ["polica"],
"Мидии": ["dagnj"],
"Минеральная вода": ["knjaz milos", "vrnjci", "negazirana voda", "prirodna voda", "mineralna voda", "aqua viva"],
"Молоко": ["mleko", "sv.mlek"],
"Молочный десерт": ["puding", "napitak mlecni"],
"Морковь": ["sargarepa"],
"Мороженое": ["sladoled", "slad.delhaize", "slad.ducale"],
"Мука": ["brasno"],
"Мусорные пакеты": ["kese za smece"],
"Мыло туалетное": ["sapun palmolive", "sapun black orchid"],
"Мюсли": ["musli"],
"Мясные деликатесы": ["pecenica dimljena", "dimljeni vrat", "slanina", "dim.svinj.spic reb", "pecenica dim", "vrat dimlj", "hajdu dimko", "perutnina pilec", "dim. vra", "dim.svinj.v", "pečena šunka", "dimljene kosti"],
"Носки": ["socks", "nazuvica"],
"Овощная заморозка": ["zamrzuta mesavina za rusku salatu"],
"Овощная смесь": ["mexicka mesavina"],
"Овощные консервы": ["kornisoni", "masl. bez košt", "grasak"],
"Овсяные хлопья": ["pahulice ovsene", "ovsene pahuljice"],
"Огурцы":["krastavac"],
"Освежитель в салон": ["tecni miris", "areon smile"],
"Отбеливатель": ["maramice za blistavo beli ves", "izbeljivac", "za izbeljivanje rublja", "dr.beck.eliminator", "lovac na boje", "vanish"],
"Пакет": ["biorazgradiva kesa", "kesa velika", "kesa za zamrzivac", "kesa tregerica", "kese ap kom", "kesa trgovacka", "dm pap. kesa recik", "kesa vjz", "medius kesa"],
"Пена для бритья": ["pena za brij"],
"Персики": ["breskva domaca"],
"Перец": ["biber crni", "biber u zrnu"],
"Подсолнечное масло": ["ulje"],
"Покупка готовой еды": ["pečena prasetina"],
"Посуда для готовки": ["serpa", "ljustac"],
"Приправы": ["paprika slatka", "majcina dusica", "lovor", "ruzmarin", "bujon govedji", "crni bib", "govedja kocka", "kotanyi"],
"Протеиновый коктейль": ["protein vanila zott", "protein sejk", "shake vanila", "protein tecni", "shake stay strong", "high protein", "imlek protein"],
"Пиво": ["pivo", "staropramen", "lowenbrau", "somersby", "corona", "san miguel", "kozel", "valjevsko", "bip"],
"Пшёнка": ["proso"],
"Разрыхлитель для теста": ["prasak za pec"],
"Расходники для кухни": ["papir za pecenje", "kese za zamrz", "ubrus", "folija", "nitril rukavice", "kese za pecenje"],
"Рис": ["riso pronto", "basmati"],
"Рулет": ["rolat jumbo roll"],
"Рыба": ["pastrmka", "losos"],
"Рыбные палочки": ["riblji stapici"],
"Сахар": ["secer kristal", "secer u prahu"],
"Свинина": ["svinjski but", "svinjski vrat bk", "sv. rebra za rostilj"],
"Сироп": ["deser.preliv"],
"Сливки": ["pavlaka za slag", "pavlaka za kuvanje", "president pavl"],
"Сметана": ["milera"],
"Соевый соус": ["sos soja", "tamari"],
"Соль": ["so mors"],
"Соус": ["terijaki", "teriyaki"],
"Сосиски": ["virsla", "pileci hot dog", "hrenovka", "greisinger knacker"],
"Средства для посудомойки": ["kapsule fairy"],
"Средство для прочистки труб": ["za otpusavanje slivnika"],
"Средство для укладки": ["taft"],
"Стиральный порошок": ["persil"],
"Столовая посуда": ["kasika"],
"Сыр": ["sir", "gauda"],
"Творог": ["urda"],
"Томателло": ["tomatello"],
"Туалетная бумага":["perfex comfort", "toalet papir", "vlaz.mar", "toalet.pap"],
"Тыква": ["bundeva"],
"Удобрение": ["univerzalni stapici"],
"Фрукты консервированные": ["kompot", "malibu ananas"],
"Хлеб": ["hleb", "h&k integralni", "putero tost"],
"Цветная капуста": ["karfiol", "brokoli"],
"Цветочный горшок": ["zardinjer"],
"Чай": ["caj", "čaj"],
"Чеснок": ["beli luk"],
"Чипсы": ["cips", "doritos", "chips", "čips"],
"Чистящее средство": ["cif", "ajax", "emsal"],
"Шоколад": ["cokolada", "mars", "kinder", "snickers", "bounty", "kit kat", "milka"],
"Электрика": ["led trak", "kabl"],
"Яблоки": ["jabuka crveni delises", "jabuka zlatni delises", "metro jabuka crveni", "jabuka ajdared", "jabuka greni", "jabuka pink", "domaća jabuka"],
"Ягоды": ["smrznute višnje"],
"Яйца": ["jaja"]

}

def simplify_name_by_store(store_name) :
    for simple_cat in store_types :
        for var in store_types[simple_cat] :
            if store_name.find(var) != -1 :
                return ("found", simple_cat)
    return ("not found", store_name)


def simplify_name_by_table(original) :
    for simple_cat in simplificator :
        for var in simplificator[simple_cat] :
            if original.find(var) != -1 :
                return ("found", simple_cat)
    return ("not found", original)


