simplificator = {
"Аксессуары для волос": ["snalica"],
"Ананас": ["ananas svez"],
"Бреф": ["bref"],
"Бурда": ["burda"],
"Валерьянка": ["valeriana"],
"Ванилин": ["vanil secer"],
"Варенье малиновое": ["slatko malina"],
"Витамины": ["magnezijum", "omega3"],
"Газировка": ["sok gazirani","aloe vera", "fanta", "7 up"],
"Говядина": ["juneci but"],
"Готовая еда на обед": ["sarma"],
"Груши": ["kruska"],
"Дрожжи": ["svezi kvasac"],
"Жевательная резинка": ["zvake", "orbit"],
"Желатин": ["zelatin"],
"Зубные щётки": ["cetka za zube"],
"Йогурт в баночке": ["jogurt grekos", "dukatos jogurt"],
"Йогурт питьевой": ["jogurt 2.8%mm", "jogurt lagani"],
"Канцтовары": ["selotejp traka", "koverte", "fascikla", "skalper", "spajalice", "stipaljke"],
"Капуста": ["kupus"],
"Картошка": ["krompir"],
"Кетчуп": ["kecap"],
"Кефир": ["kefir"],
"Колбаса": ["mortadella", "salama", "kobasica"],
"Кондиционер для стирки": ["lenor"],
"Кокос": ["kokos napitak"],
"Конфеты": ["haribo"],
"Кости на суп": ["junece mesnate kosti"],
"Кофе растворимый": ["nescafe"],
"Круассаны": ["7days"],
"Курица":["pile ", "pileca krila"],
"Лимонная кислота":["limuntus"],
"Лук": ["crni luk", "luk mladi", "luk crni"],
"Майонез": ["majonez"],
"Макароны": ["nudle", "testenina"],
"Масло": ["maslac"],
"Минеральная вода":["knjaz milos", "vrnjci"],
"Молоко": ["mleko"],
"Молочный десерт": ["puding"],
"Морковь": ["sargarepa"],
"Мороженое": ["sladoled", "slad.delhaize", "slad.ducale"],
"Мука": ["brasno"],
"Мюсли": ["musli"],
"Мясные деликатесы": ["pecenica dimljena", "dimljeni vrat", "slanina", "dim.svinj.spic reb", "pecenica dim", "vrat dimlj", "hajdu dimko"],
"Носки": ["socks", "nazuvica"],
"Овощная заморозка": ["zamrzuta mesavina za rusku salatu"],
"Овощная смесь": ["mexicka mesavina"],
"Овсяные хлопья": ["pahulice ovsene", "ovsene pahuljice"],
"Огурцы":["krastavac"],
"Отбеливатель": ["maramice za blistavo beli ves", "izbeljivac", "za izbeljivanje rublja", "dr.beck.eliminator", "lovac na boje"],
"Пакет": ["biorazgradiva kesa", "kesa velika", "kesa za zamrzivac", "kesa tregerica", "kese ap kom", "kesa trgovacka", "dm pap. kesa recik", "kesa vjz"],
"Персики": ["breskva domaca"],
"Подсолнечное масло": ["ulje"],
"Посуда для готовки": ["serpa"],
"Приправы": ["paprika slatka", "majcina dusica", "lovor", "ruzmarin", "bujon govedji", "crni bib", "govedja kocka"],
"Протеиновый коктейль": ["protein vanila zott", "protein sejk", "shake vanila", "protein tecni", "shake stay strong"],
"Пиво": ["pivo", "staropramen", "lowenbrau", "somersby"],
"Разрыхлитель для теста": ["prasak za pec"],
"Расходники для кухни": ["papir za pecenje"],
"Рис": ["riso pronto"],
"Рулет": ["rolat jumbo roll"],
"Рыба": ["pastrmka"],
"Рыбные палочки": ["riblji stapici"],
"Сахар": ["secer kristal", "secer u prahu"],
"Свинина": ["svinjski but", "svinjski vrat bk"],
"Сироп": ["deser.preliv"],
"Сливки": ["pavlaka za slag", "pavlaka za kuvanje"],
"Сметана": ["mileram"],
"Соевый соус": ["sos soja", "tamari"],
"Соль": ["so mors"],
"Соус": ["terijaki"],
"Сосиски": ["virsla", "pileci hot dog"],
"Средство для прочистки труб": ["za otpusavanje slivnika"],
"Средство для укладки": ["taft"],
"Стиральный порошок": ["persil"],
"Сыр": ["sir", "gauda"],
"Томателло": ["tomatello"],
"Туалетная бумага":["perfex comfort", "toalet papir"],
"Хлеб": ["hleb"],
"Чай": ["caj"],
"Чеснок": ["beli luk"],
"Чипсы": ["cips", "doritos", "chips"],
"Чистящее средство": ["cif"],
"Шоколад": ["cokolada", "mars", "kinder", "snickers", "bounty", "kit kat"],
"Яблоки": ["jabuka crveni delises"],
"Яйца": ["jaja"]

}


def simplify_name_by_table(original) :
    for simple_cat in simplificator :
        for var in simplificator[simple_cat] :
            if original.find(var) != -1 :
                return ("found", simple_cat)
    return ("not found", original)
